version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3307:3306"
    restart: always

  ingestion:
    build:
      context: ./images/ingestion
    command: ["python", "/ingest.py"]
    volumes:
      - ./data:/data
    depends_on:
      - database

  summary:
    build:
      context: ./images/summary
    command: ["python", "/summarize.py"]
    volumes:
      - ./data:/data
    depends_on:
      - database

  
